endpoint:
  base_url: https://openrouter.ai/api/v1
  api_key:
  model: google/gemini-2.5-pro-preview-03-25
  #model: anthropic/claude-3.7-sonnet
  gen_config:
    temperature: 1
    top_p: 0.95
    max_completion_tokens: 8192

topic: economics
num_exercises: 100
batch_size: 25
history_size: 35

output_info:
  dir: ./output-raw
  fname: "{topic}-raw-{timestamp}.jsonl"
