endpoint:
  base_url: https://openrouter.ai/api/v1
  api_key:
  model: google/gemini-2.0-flash-001
  gen_config:
    temperature: 1
    top_p: 1
    max_completion_tokens: 2048

dataset:
  path: mferraretto/fpfeval
  name: en
  splits:
    - math
    - law
    - economics
    - medicine
  #token:

batch_size: 4

output_info:
  dir: ./translated
  fname: mcq-{topic}-it.jsonl
